spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file:~/my_db/my_db;MODE=LEGACY
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: "org.hibernate.dialect.H2Dialect"
server:
  ip: '127.0.0.3'
  port: 8081
  auth:
    secret: "secret_+123ff"